# Only homebrew OSX GUI applications - everything else should be done via home-manager packages!

tap "homebrew/bundle"
tap "homebrew/cask"

# From casks
cask "alfred"
cask "android-studio"
cask "appcleaner"
cask "balenaetcher"
cask "brave-browser"
cask "db-browser-for-sqlite"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "itsycal"
cask "keepingyouawake"
cask "libreoffice"
cask "little-snitch"
cask "mattermost"
cask "omnidisksweeper"
cask "openmtp"
cask "postman"
cask "rectangle"
cask "skype"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "utm"
cask "vivaldi"
cask "vlc"

brew "scrcpy"
