# Host `short` — one file: host data + the host's composed aspect.
{ den, ... }:
let
  # TODO(1.3): replace with the clan-managed key. Lifted from machines/short.
  authorizedKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA6h5RafG9hYqgT3nviJO9P9eEUEAHJlIEqFWfoxFOP6";
in
{
  # short has exactly one user
  den.hosts.x86_64-linux.short.users.df = { };

  # The host aspect (auto-applied to `short`) — composes the role, the hardware
  # wiring aspects, and the irreducible host-specific data (facter report, disk).
  den.aspects.short = {
    includes = with den.aspects; [
      # Hardware
      hardware.bluetooth
      hardware.cpu.amd
      hardware.cpu.auto-cpufreq
      hardware.facter
      hardware.firmware
      hardware.gpu.amd
      hardware.keyboard
      hardware.printing
      hardware.storage.disko
      hardware.storage.ssd
      hardware.touchpad
      hardware.tweaks
      hardware.utils

      roles.default
      roles.desktop
      roles.dev
      roles.workstation

      virtualization.libvirt
      virtualisation.vm-login # test-only
    ];

    nixos = _: {
      # Real hardware detection — same report clan generates/uses.
      facter.reportPath = ./short.facter.json;

      # Disk layout, lifted verbatim from machines/short/disko.nix.
      # (Generated by clan; changing it requires wiping + reinstalling.)
      # boot.loader.grub = {
      #   enable = true;
      #   efiSupport = true;
      #   efiInstallAsRemovable = true;
      # };
      disko.devices.disk.main = {
        name = "main-9388885dccc64814af644d0f18cee9ac";
        device = "/dev/disk/by-path/pci-0000:04:00.0";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            boot = {
              size = "1M";
              type = "EF02"; # for grub MBR
              priority = 1;
            };
            ESP = {
              type = "EF00";
              size = "500M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" ];
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };

      users.users.root.openssh.authorizedKeys.keys = [ authorizedKey ];
    };
  };
}
