# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ohci_pci" "ehci_pci" "virtio_pci" "ahci" "usbhid" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fcc98615-6f30-4c1f-b757-5ddccd1afc7e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-4b5d2fb8-a8a9-4288-8ec3-41705b4ccbb0".device = "/dev/disk/by-uuid/4b5d2fb8-a8a9-4288-8ec3-41705b4ccbb0";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2676-B121";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/1c063e91-c6ba-4c4a-a4ea-07a6dd216af8";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s8.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
